services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service-app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: order_service
      DB_USERNAME: root
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - rabbitmq
    command: >
      sh -c "
      sleep 10 &&
      php artisan config:clear &&
      php artisan cache:clear &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "


  mysql:
    image: mysql:8.0
    container_name: order-service-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: order_service
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - order-service-mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: order-service-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  order-service-mysql-data:

